---
# This playbook updates all Docker containers on a Docker host


# Playbook
- name: Docker update
  hosts: docker

  # Settings
  vars:
    ansible_ssh_private_key_file: "{{ ssh_keys_base_dir }}/{{ host_hostname }}"
