---
# This playbook only performs security updates on the host


# Playbook
- name: System update security
  hosts: all

  # Settings
  vars:
    ansible_ssh_private_key_file: "{{ ssh_keys_base_dir }}/{{ host_hostname }}"
